// automatically generated by the FlatBuffers compiler, do not modify

package bpio

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ConfigurationRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ConfigurationRequest {
        __init(_i, _bb)
        return this
    }
    val mode : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val modeAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun modeInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val modeConfiguration : bpio.ModeConfiguration? get() = modeConfiguration(bpio.ModeConfiguration())
    fun modeConfiguration(obj: bpio.ModeConfiguration) : bpio.ModeConfiguration? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val modeBitorderMsb : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val modeBitorderLsb : Boolean
        get() {
            val o = __offset(10)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val psuDisable : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val psuEnable : Boolean
        get() {
            val o = __offset(14)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val psuSetMv : UInt
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val psuSetMa : UShort
        get() {
            val o = __offset(18)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 300u
        }
    val pullupDisable : Boolean
        get() {
            val o = __offset(20)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val pullupEnable : Boolean
        get() {
            val o = __offset(22)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val ioDirectionMask : UByte
        get() {
            val o = __offset(24)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    val ioDirection : UByte
        get() {
            val o = __offset(26)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    val ioValueMask : UByte
        get() {
            val o = __offset(28)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    val ioValue : UByte
        get() {
            val o = __offset(30)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    val ledResume : Boolean
        get() {
            val o = __offset(32)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    fun ledColor(j: Int) : UInt {
        val o = __offset(34)
        return if (o != 0) {
            bb.getInt(__vector(o) + j * 4).toUInt()
        } else {
            0u
        }
    }
    val ledColorLength : Int
        get() {
            val o = __offset(34); return if (o != 0) __vector_len(o) else 0
        }
    val ledColorAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(34, 4)
    fun ledColorInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 34, 4)
    val printString : String?
        get() {
            val o = __offset(36)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val printStringAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(36, 1)
    fun printStringInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 36, 1)
    val hardwareBootloader : Boolean
        get() {
            val o = __offset(38)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val hardwareReset : Boolean
        get() {
            val o = __offset(40)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val hardwareSelftest : Boolean
        get() {
            val o = __offset(42)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsConfigurationRequest(_bb: ByteBuffer): ConfigurationRequest = getRootAsConfigurationRequest(_bb, ConfigurationRequest())
        fun getRootAsConfigurationRequest(_bb: ByteBuffer, obj: ConfigurationRequest): ConfigurationRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createConfigurationRequest(builder: FlatBufferBuilder, modeOffset: Int, modeConfigurationOffset: Int, modeBitorderMsb: Boolean, modeBitorderLsb: Boolean, psuDisable: Boolean, psuEnable: Boolean, psuSetMv: UInt, psuSetMa: UShort, pullupDisable: Boolean, pullupEnable: Boolean, ioDirectionMask: UByte, ioDirection: UByte, ioValueMask: UByte, ioValue: UByte, ledResume: Boolean, ledColorOffset: Int, printStringOffset: Int, hardwareBootloader: Boolean, hardwareReset: Boolean, hardwareSelftest: Boolean) : Int {
            builder.startTable(20)
            addPrintString(builder, printStringOffset)
            addLedColor(builder, ledColorOffset)
            addPsuSetMv(builder, psuSetMv)
            addModeConfiguration(builder, modeConfigurationOffset)
            addMode(builder, modeOffset)
            addPsuSetMa(builder, psuSetMa)
            addHardwareSelftest(builder, hardwareSelftest)
            addHardwareReset(builder, hardwareReset)
            addHardwareBootloader(builder, hardwareBootloader)
            addLedResume(builder, ledResume)
            addIoValue(builder, ioValue)
            addIoValueMask(builder, ioValueMask)
            addIoDirection(builder, ioDirection)
            addIoDirectionMask(builder, ioDirectionMask)
            addPullupEnable(builder, pullupEnable)
            addPullupDisable(builder, pullupDisable)
            addPsuEnable(builder, psuEnable)
            addPsuDisable(builder, psuDisable)
            addModeBitorderLsb(builder, modeBitorderLsb)
            addModeBitorderMsb(builder, modeBitorderMsb)
            return endConfigurationRequest(builder)
        }
        fun startConfigurationRequest(builder: FlatBufferBuilder) = builder.startTable(20)
        fun addMode(builder: FlatBufferBuilder, mode: Int) = builder.addOffset(0, mode, 0)
        fun addModeConfiguration(builder: FlatBufferBuilder, modeConfiguration: Int) = builder.addOffset(1, modeConfiguration, 0)
        fun addModeBitorderMsb(builder: FlatBufferBuilder, modeBitorderMsb: Boolean) = builder.addBoolean(2, modeBitorderMsb, false)
        fun addModeBitorderLsb(builder: FlatBufferBuilder, modeBitorderLsb: Boolean) = builder.addBoolean(3, modeBitorderLsb, false)
        fun addPsuDisable(builder: FlatBufferBuilder, psuDisable: Boolean) = builder.addBoolean(4, psuDisable, false)
        fun addPsuEnable(builder: FlatBufferBuilder, psuEnable: Boolean) = builder.addBoolean(5, psuEnable, false)
        fun addPsuSetMv(builder: FlatBufferBuilder, psuSetMv: UInt) = builder.addInt(6, psuSetMv.toInt(), 0)
        fun addPsuSetMa(builder: FlatBufferBuilder, psuSetMa: UShort) = builder.addShort(7, psuSetMa.toShort(), 300)
        fun addPullupDisable(builder: FlatBufferBuilder, pullupDisable: Boolean) = builder.addBoolean(8, pullupDisable, false)
        fun addPullupEnable(builder: FlatBufferBuilder, pullupEnable: Boolean) = builder.addBoolean(9, pullupEnable, false)
        fun addIoDirectionMask(builder: FlatBufferBuilder, ioDirectionMask: UByte) = builder.addByte(10, ioDirectionMask.toByte(), 0)
        fun addIoDirection(builder: FlatBufferBuilder, ioDirection: UByte) = builder.addByte(11, ioDirection.toByte(), 0)
        fun addIoValueMask(builder: FlatBufferBuilder, ioValueMask: UByte) = builder.addByte(12, ioValueMask.toByte(), 0)
        fun addIoValue(builder: FlatBufferBuilder, ioValue: UByte) = builder.addByte(13, ioValue.toByte(), 0)
        fun addLedResume(builder: FlatBufferBuilder, ledResume: Boolean) = builder.addBoolean(14, ledResume, false)
        fun addLedColor(builder: FlatBufferBuilder, ledColor: Int) = builder.addOffset(15, ledColor, 0)
        @kotlin.ExperimentalUnsignedTypes
        fun createLedColorVector(builder: FlatBufferBuilder, data: UIntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addInt(data[i].toInt())
            }
            return builder.endVector()
        }
        fun startLedColorVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addPrintString(builder: FlatBufferBuilder, printString: Int) = builder.addOffset(16, printString, 0)
        fun addHardwareBootloader(builder: FlatBufferBuilder, hardwareBootloader: Boolean) = builder.addBoolean(17, hardwareBootloader, false)
        fun addHardwareReset(builder: FlatBufferBuilder, hardwareReset: Boolean) = builder.addBoolean(18, hardwareReset, false)
        fun addHardwareSelftest(builder: FlatBufferBuilder, hardwareSelftest: Boolean) = builder.addBoolean(19, hardwareSelftest, false)
        fun endConfigurationRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
