// automatically generated by the FlatBuffers compiler, do not modify

package bpio

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class RequestPacket : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : RequestPacket {
        __init(_i, _bb)
        return this
    }
    val versionMajor : UByte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    val minimumVersionMinor : UShort
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val contentsType : UByte
        get() {
            val o = __offset(8)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    fun contents(obj: Table) : Table? {
        val o = __offset(10); return if (o != 0) __union(obj, o + bb_pos) else null
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsRequestPacket(_bb: ByteBuffer): RequestPacket = getRootAsRequestPacket(_bb, RequestPacket())
        fun getRootAsRequestPacket(_bb: ByteBuffer, obj: RequestPacket): RequestPacket {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createRequestPacket(builder: FlatBufferBuilder, versionMajor: UByte, minimumVersionMinor: UShort, contentsType: UByte, contentsOffset: Int) : Int {
            builder.startTable(4)
            addContents(builder, contentsOffset)
            addMinimumVersionMinor(builder, minimumVersionMinor)
            addContentsType(builder, contentsType)
            addVersionMajor(builder, versionMajor)
            return endRequestPacket(builder)
        }
        fun startRequestPacket(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addVersionMajor(builder: FlatBufferBuilder, versionMajor: UByte) = builder.addByte(0, versionMajor.toByte(), 0)
        fun addMinimumVersionMinor(builder: FlatBufferBuilder, minimumVersionMinor: UShort) = builder.addShort(1, minimumVersionMinor.toShort(), 0)
        fun addContentsType(builder: FlatBufferBuilder, contentsType: UByte) = builder.addByte(2, contentsType.toByte(), 0)
        fun addContents(builder: FlatBufferBuilder, contents: Int) = builder.addOffset(3, contents, 0)
        fun endRequestPacket(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
