// automatically generated by the FlatBuffers compiler, do not modify

package bpio

@Suppress("unused")
class RequestPacketContents private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val StatusRequest: UByte = 1u
        const val ConfigurationRequest: UByte = 2u
        const val DataRequest: UByte = 3u
    }
}
