// automatically generated by the FlatBuffers compiler, do not modify

package bpio

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ResponsePacket : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ResponsePacket {
        __init(_i, _bb)
        return this
    }
    val error : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val errorAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun errorInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val contentsType : UByte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    fun contents(obj: Table) : Table? {
        val o = __offset(8); return if (o != 0) __union(obj, o + bb_pos) else null
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsResponsePacket(_bb: ByteBuffer): ResponsePacket = getRootAsResponsePacket(_bb, ResponsePacket())
        fun getRootAsResponsePacket(_bb: ByteBuffer, obj: ResponsePacket): ResponsePacket {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createResponsePacket(builder: FlatBufferBuilder, errorOffset: Int, contentsType: UByte, contentsOffset: Int) : Int {
            builder.startTable(3)
            addContents(builder, contentsOffset)
            addError(builder, errorOffset)
            addContentsType(builder, contentsType)
            return endResponsePacket(builder)
        }
        fun startResponsePacket(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addError(builder: FlatBufferBuilder, error: Int) = builder.addOffset(0, error, 0)
        fun addContentsType(builder: FlatBufferBuilder, contentsType: UByte) = builder.addByte(1, contentsType.toByte(), 0)
        fun addContents(builder: FlatBufferBuilder, contents: Int) = builder.addOffset(2, contents, 0)
        fun endResponsePacket(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishResponsePacketBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset)
        fun finishSizePrefixedResponsePacketBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset)
    }
}
