// automatically generated by the FlatBuffers compiler, do not modify

package bpio

@Suppress("unused")
class ResponsePacketContents private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val StatusResponse: UByte = 1u
        const val ConfigurationResponse: UByte = 2u
        const val DataResponse: UByte = 3u
    }
}
