// automatically generated by the FlatBuffers compiler, do not modify

package bpio

@Suppress("unused")
class StatusRequestTypes private constructor() {
    companion object {
        const val All: Byte = 0
        const val Version: Byte = 1
        const val Mode: Byte = 2
        const val Pullup: Byte = 3
        const val PSU: Byte = 4
        const val ADC: Byte = 5
        const val IO: Byte = 6
        const val Disk: Byte = 7
        const val LED: Byte = 8
    }
}
